spring:
  datasource:
    url: jdbc:mysql://localhost:3306/edts
    username: root
    password: ayamgoreng
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always
